language: minimal

stages:
  - name: fast_check
    if: type = push OR (type = pull_request AND slug != "KjellMorgenstern/travis-aws")
  - name: build_and_pack
    if: type = push

jobs:
  include:
    - stage: build_and_pack
      name: Fedora
      os: linux
      language: minimal
      services:
        - docker
      before_install:
        - docker pull fritzing/build:fedora-31
      script:
        - id
        - echo $UID
        - docker/release-linux.sh fedora-31 $TRAVIS_COMMIT-debug-continuous-$TRAVIS_BUILD_NUMBER.fedora-31


    - stage: build_and_pack
      name: Bionic
      os: linux
      language: minimal
      services:
        - docker
      before_install:
        - docker pull fritzing/build:bionic
      script:
        - id
        - echo $UID
        - docker/release-linux.sh bionic $TRAVIS_COMMIT-debug-continuous-$TRAVIS_BUILD_NUMBER.bionic


