language: minimal

env:
  global:

jobs:
  include:
    - os: windows
      language: cpp

      env:
      before_install:
        - mkdir -p ~/$TRAVIS_BUILD_NUMBER
        - ./aws_tasks.sh setup

      script:
        - ./build-windows.bat
        - ls .
        - ls ..
        - cp $TRAVIS_BUILD_DIR/../release123/fritzing.pc.zip ~/$TRAVIS_BUILD_NUMBER


      after_success:
        - ./aws_tasks.sh synchronize_up
