language: minimal

stages:
  - name: fast_check
    if: type = push OR (type = pull_request AND slug != "KjellMorgenstern/travis-aws")
  - name: build_and_pack
    if: type = push

jobs:
  include:
    - stage: fast_check
      os: osx
      language: cpp
      osx_image: xcode10.1

      addons:
        homebrew:
          packages:
          - md5sha1sum
          update: true

      script:
        - echo "test" > test.txt
        - md5sum test.txt

    - stage: fast_check
      os: osx
      language: cpp
      osx_image: xcode10.2

      # addons:
      #   homebrew:
      #     packages:
      #     - qt5

      script:
        - echo "test" > test.txt
        - md5sum test.txt


    # - stage: build_and_pack
    #   os: windows
    #   language: cpp

    #   env:
    #   before_install:
    #     - mkdir -p ~/$TRAVIS_BUILD_NUMBER
    #     - ./aws_tasks.sh setup

    #   script:
    #     - ./build-windows.bat
    #     - ls .
    #     - ls ..
    #     - cp $TRAVIS_BUILD_DIR/../release123/fritzing.pc.zip ~/$TRAVIS_BUILD_NUMBER


    #   after_success:
    #     - ./aws_tasks.sh synchronize_up
