language: minimal

env:
  global:

jobs:
  include:
    - os: windows
      language: cpp

      env:
      before_install:
        - mkdir -p ~/$TRAVIS_BUILD_NUMBER
        - export "PATH=/c/Program Files/Amazon/AWSCLI/bin:$PATH"
        - ./aws_tasks.sh setup

      script:
          - echo "Hello world" > ~/$TRAVIS_BUILD_NUMBER/hello_windows.txt

      after_success:
        - ./aws_tasks.sh synchronize_up
