language: minimal

stages:
  - name: fast_check
    if: type = push OR (type = pull_request AND slug != "KjellMorgenstern/travis-aws")
  - name: build_and_pack
    if: type = push
  - name: deploy_to_github

jobs:
  include:
    - stage: build_and_pack
      name: Fedora
      os: linux
      language: minimal
      services:
        - docker
      before_install:
        - (cd docker && docker build --tag fritzing/build:fedora-30 .)
      script:
        - id
        - echo $UID
#        - docker/release-linux.sh fedora-30 $TRAVIS_COMMIT-debug-continuous-$TRAVIS_BUILD_NUMBER.fedora-30


    # - stage: build_and_pack
    #   name: Bionic
    #   os: linux
    #   language: minimal
    #   services:
    #     - docker
    #   before_install:
    #     - docker pull fritzing/build:bionic
    #   script:
    #     - id
    #     - echo $UID
    #     - docker/release-linux.sh bionic $TRAVIS_COMMIT-debug-continuous-$TRAVIS_BUILD_NUMBER.bionic


    - stage: deploy_to_github
      before_install:
#        - tools/aws_tasks.sh setup
#        - tools/aws_tasks.sh synchronize_down
      before_deploy:
        - git config --local user.name "Travis C.D."
        - git config --local user.email "travis@fritzing.org"
        - git tag CD-$TRAVIS_BUILD_NUMBER
      deploy:
        - provider: releases
          draft: true
          api_key:
            secure: "ndzX3gAwth3jsLQobNvYZKERGsP6OjsLNIj/CiIw1eGzJn9Di6bB0aksIBiRU8Sp5zGdMUjxiQk/qgZg/vnce+oUiQM8c1PFgGh1b04W57M8NnnGYsfMa9b8kgEzlmlpP4qSD6SlG5FI29JuOAQqQWHD3ywnsy9tiu5dn84k735gLfTnuIzFmQgvl5zil8G2kMSLMY0EIC8bgWbn8JRsEfBqF7FvbJOmmsww/ADRJx2z6iOhOmTu23qZOIq6GNG8MTyp0jW6yZsNP0Nyum966pqsu6cwyHVuXA4iIRBgE1022PoQfN9F7cLiuskl33xbl5FoKQS7iw7W3wUH0vmyd3XuiBBpoDz2A2iPghMS/7Z31T5rCWgWb9SDDelScz3y9ESlabmmOBVEx633eWtrXG5poiMLJshLyR3d+uCm5C5fIyPn++CxwMkBR/anWMJBlCYX8CYSLBJd5Kz+J/vvc6XTgm1D4+oUYBcrhRs3fiRlKY72RHLy8V3b9ji+oIpnz5ZqguSS1WpF74T+zESyb/dtL0dfAewxmQg1XdOzcmRgWP80Uc3Mxb3laImrBJLSPXi0eR0V5Y0n6RVub3FQOhzNx5+s0jaGbzYJJScKC1eOLbupdSuKEUOG5n4I8IsHTzr3EIzhMyI7vSK0w4bKVdSxLYuVcXV8Bf9Kc+7yZvg="
          file_glob: true
          file: $HOME/$TRAVIS_BUILD_NUMBER/*
          skip_cleanup: true

      after_deploy:
        #- tools/aws_tasks.sh cleanup
